spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yorkshin
    username: root
    password: 8310
  jpa:
    hibernate:
      #???? ?????? DDL(Data Definition Language)? ???? ???? ???? ????? ????? ddl-auto ??
      #???????? ?? ??? ??? ???? ???? ??? ddl-auto ??? ?? ??? ?? Entity ??? ???? ???? ??? ? ??
      #create ??? none ??? ?? ?? - create ??? ???? db? ??? ??? ?? ???? ??? ? ??
      ddl-auto: none
      #??? ??? ??
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
